Develop
Dmytry95/IT-Company-Task-Manager pull request #1
Opened 2023-06-21 11:31 UTC by Dmytry95

2023-06-21 11:44 UTC, Dmytry95 commented
1)Link to current authenticated user page and hover with links to other pages
![image](https://github.com/Dmytry95/IT-Company-Task-Manager/assets/126564500/935c9ad8-98f3-4a54-bba7-c1f96e07e9ce)

2)Position/TaskType/Page visits counters in first block of home page. 
![image](https://github.com/Dmytry95/IT-Company-Task-Manager/assets/126564500/f965d681-40f3-43bb-8d78-90b9733f74aa)


3)Task creation link in second block of home page
![image](https://github.com/Dmytry95/IT-Company-Task-Manager/assets/126564500/96000087-c68b-45ec-bd8c-b1f05782c93e)

4)Workers page with search form, detail links and tasks assigned count, create button(Pagination included)

![image](https://github.com/Dmytry95/IT-Company-Task-Manager/assets/126564500/ab823c59-cb81-4d1a-814b-3cc443747a5a)

5)Worker detail page with delete/update buttons and tasks assigned(link per task)

![image](https://github.com/Dmytry95/IT-Company-Task-Manager/assets/126564500/33f7a1f1-89e4-4fbc-9db5-215c5277c205)

6) Worker update form:

![image](https://github.com/Dmytry95/IT-Company-Task-Manager/assets/126564500/042f6b2c-5950-408c-b99f-969df8e74526)


7) Worker create form :

![image](https://github.com/Dmytry95/IT-Company-Task-Manager/assets/126564500/1f8be940-1c38-4df9-8499-326841ca720c)

8)Task list page with create button(available only for users with CEO/Project Managet position) and search field(Pagination included)

![image](https://github.com/Dmytry95/IT-Company-Task-Manager/assets/126564500/1dacaeda-5a96-428b-ba47-e4c2ff01f9cc)

9) Task detail page with update button, assign/misassign to current user button and list with assigned workers(link per worker)

![image](https://github.com/Dmytry95/IT-Company-Task-Manager/assets/126564500/5298d204-a7e1-4425-bcb6-a4cc05ecbadb)

10) Task update page

![image](https://github.com/Dmytry95/IT-Company-Task-Manager/assets/126564500/09f6bd99-572e-47a3-8d4e-213c2a23a72c)

11) Task create page

![image](https://github.com/Dmytry95/IT-Company-Task-Manager/assets/126564500/ed21085e-71d5-44ed-8251-60f1d30916ed)

2023-06-22 11:12 UTC, Dmytry95 commented
![task_manager_models_scheme](https://github.com/Dmytry95/IT-Company-Task-Manager/assets/126564500/160bf1f7-bcd6-4321-883e-65c60df9f9db)

2023-06-22 14:55 UTC, Grayder0152 requested changes

2023-06-22 14:55 UTC, Grayder0152 commented on task_manager/forms.py
> +    AuthenticationForm, UsernameField
Use `()` instead of `\`

2023-06-22 14:55 UTC, Grayder0152 commented on task_manager/models.py
> +               f"position: {self.position.name if self.position else None})"
use `()` instead of `\`

2023-06-22 14:55 UTC, Grayder0152 commented on task_manager/urls.py
> +    ToggleAssignToTaskView, WorkerDeleteView, UserLogoutView
Use `()` instead of `\`

2023-06-22 14:55 UTC, Grayder0152 commented on task_manager/views.py
> +    WorkerSearchForm, TaskSearchForm, TaskForm, WorkerForm
Use `()` instead of `\`

2023-06-22 14:55 UTC, Grayder0152 commented on task_manager/views.py
> +        context = super(WorkerListView, self).get_context_data(**kwargs)
```suggestion
        context = super().get_context_data(**kwargs)

```

2023-08-11 11:30 UTC, closed without merging